# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18m2pjaF-8rDl-yh3gKpCBtJxVnSVm0u6
"""

import streamlit as st
import streamlit.components.v1 as components
import qrcode
from io import BytesIO

# 1. Настройка страницы Streamlit (должна быть первой командой)
st.set_page_config(
    page_title="MVP Защита | Я-профессионал. Команда 8",
    page_icon="🍏",
    layout="wide",
    initial_sidebar_state="expanded"
)

# 2. Боковая панель для жюри (с генерацией QR-кода)
with st.sidebar:
    st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/X5_Group_logo.svg/1200px-X5_Group_logo.svg.png", width=150)
    st.markdown("### Команда 8")
    st.markdown("**Трек:** Продуктовый менеджмент")
    st.markdown("**Тема:** Оптимизация издержек (Ультра-Фреш)")

    st.divider()

    st.markdown("#### 📱 Открыть на смартфоне")
    # Сюда вы вставите ссылку, которую вам выдаст Streamlit Cloud после деплоя
    app_url = st.text_input("URL приложения (для QR):", value="https://x5-team8-mvp.streamlit.app")

    if app_url:
        # Генерация QR-кода
        qr = qrcode.QRCode(version=1, box_size=10, border=4)
        qr.add_data(app_url)
        qr.make(fit=True)
        img = qr.make_image(fill_color="#59A83F", back_color="white")

        # Конвертация изображения для отображения в Streamlit
        buf = BytesIO()
        img.save(buf, format="PNG")
        st.image(buf, caption="Отсканируйте для просмотра", use_column_width=True)

# 3. HTML-код нашего инфографика
html_content = """
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">

    <style>
        body { font-family: 'Inter', sans-serif; background-color: #F3F4F6; color: #1F2937; margin: 0; padding: 0; }
        .chart-container { position: relative; width: 100%; max-width: 100%; height: 300px; margin: 0 auto; }
        @media (min-width: 768px) { .chart-container { height: 380px; } }
        .plotly-container { position: relative; width: 100%; height: 380px; margin: 0 auto; }
        .corp-card { background: #FFFFFF; border: 1px solid #E5E7EB; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); border-radius: 12px; overflow: hidden; }
        .x5-green-text { color: #59A83F; }
        .section-marker { display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 28px; background-color: #59A83F; color: #FFFFFF; font-weight: 800; font-size: 0.75rem; margin-right: 12px; border-radius: 6px; letter-spacing: 0.05em; }
        .roadmap-line-desktop { position: absolute; top: 24px; left: 10%; right: 10%; height: 2px; background-color: #E5E7EB; z-index: 0; }

        /* Скрываем скроллбар внутри iframe Streamlit для красоты */
        ::-webkit-scrollbar { width: 8px; }
        ::-webkit-scrollbar-track { background: #F3F4F6; }
        ::-webkit-scrollbar-thumb { background: #D1D5DB; border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: #9CA3AF; }
    </style>
</head>
<body class="antialiased pb-24 text-gray-800">

    <header class="bg-white shadow-sm sticky top-0 z-50 border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex flex-col sm:flex-row justify-between items-center gap-4">
            <div class="flex items-center gap-4">
                <div class="flex items-center justify-center font-extrabold text-2xl tracking-tighter text-[#59A83F]">
                    X5 <span class="text-gray-800 ml-1 font-bold">Group</span>
                </div>
                <div class="hidden sm:block h-6 w-px bg-gray-300"></div>
                <h1 class="text-sm sm:text-lg font-semibold text-gray-700">Я — профессионал. Команда 8</h1>
            </div>
        </div>
    </header>

    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8 sm:mt-12 space-y-8 sm:space-y-12">
        <section class="max-w-4xl">
            <h2 class="text-3xl sm:text-4xl md:text-5xl font-bold mb-6 text-gray-900 leading-tight">
                Оптимизация издержек категории <span class="x5-green-text">«Ультра-Фреш»</span>
            </h2>
            <div class="bg-white p-5 rounded-lg border-l-4 border-[#59A83F] shadow-sm">
                <p class="text-base sm:text-lg text-gray-600 leading-relaxed font-medium">
                    В условиях макроэкономической нестабильности (BANI-мир 2026) категория готовой еды генерирует критический уровень издержек на списания при низкой доле в чеке. Решение: внедрение ML-алгоритма динамического ценообразования (Smart Markdown) для конвертации потенциальных убытков в выручку.
                </p>
            </div>
        </section>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8">
            <div class="corp-card p-6 sm:p-8 flex flex-col">
                <div class="flex items-center mb-4 border-b border-gray-100 pb-4">
                    <span class="section-marker">01</span><h3 class="text-lg sm:text-xl font-bold text-gray-800">Бизнес-проблема: Списания</h3>
                </div>
                <p class="text-sm text-gray-600 mb-6">Категория кулинарии формирует незначительную часть выручки, однако из-за короткого срока годности является основным драйвером убытков от утилизации.</p>
                <div class="w-full flex-grow"><div class="chart-container"><canvas id="wastageChart"></canvas></div></div>
            </div>

            <div class="corp-card p-6 sm:p-8 flex flex-col">
                <div class="flex items-center mb-4 border-b border-gray-100 pb-4">
                    <span class="section-marker">02</span><h3 class="text-lg sm:text-xl font-bold text-gray-800">Клиентский профиль (CusDev)</h3>
                </div>
                <p class="text-sm text-gray-600 mb-6">Фокус потребителя сместился на рациональную экономию. Покупатели готовы брать товары с истекающим сроком только при наличии явной скидки.</p>
                <div class="w-full flex-grow"><div class="chart-container"><canvas id="consumerChart"></canvas></div></div>
            </div>
        </div>

        <section class="corp-card border-t-4 border-[#59A83F]">
            <div class="p-6 sm:p-8 border-b border-gray-100 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                <div class="flex-1">
                    <div class="flex items-center mb-2">
                        <span class="section-marker">03</span><h3 class="text-xl sm:text-2xl font-bold text-gray-800">Архитектура решения: Smart Markdown</h3>
                    </div>
                    <p class="text-gray-600 text-sm mt-2">Автоматизированная система динамической уценки. Цель: распродать остатки до истечения срока годности без участия персонала.</p>
                </div>
                <div class="bg-[#59A83F] bg-opacity-10 border border-[#59A83F] px-6 py-4 rounded-lg flex flex-col items-center justify-center shrink-0">
                    <span class="text-xs uppercase font-bold text-gray-600 mb-1">Target KPI</span>
                    <span class="text-3xl font-extrabold text-[#59A83F]">-40%</span>
                    <span class="text-xs text-gray-500 mt-1">объема списаний</span>
                </div>
            </div>
            <div class="p-6 sm:p-8 bg-gray-50 flex flex-col md:flex-row justify-between items-center gap-4">
                <div class="bg-white border border-gray-200 rounded-lg p-5 w-full md:w-1/3 shadow-sm text-center relative z-10"><div class="text-xs font-bold text-gray-400 mb-2 tracking-widest">ШАГ 1</div><h4 class="font-bold text-gray-800 mb-2">ML-Аналитика</h4><p class="text-xs text-gray-500">Предиктивный мониторинг остатков и сроков годности SKU</p></div>
                <div class="text-gray-300 font-bold text-2xl rotate-90 md:rotate-0">➔</div>
                <div class="bg-[#59A83F] border border-[#488732] rounded-lg p-5 w-full md:w-1/3 shadow-md text-center transform md:scale-105 relative z-10"><div class="text-xs font-bold text-green-200 mb-2 tracking-widest">ШАГ 2 (ЯДРО)</div><h4 class="font-bold text-white mb-2">Динамический прайсинг</h4><p class="text-xs text-green-50">Алгоритмический расчет оптимальной скидки (30-50%)</p></div>
                <div class="text-gray-300 font-bold text-2xl rotate-90 md:rotate-0">➔</div>
                <div class="bg-white border border-gray-200 rounded-lg p-5 w-full md:w-1/3 shadow-sm text-center relative z-10"><div class="text-xs font-bold text-gray-400 mb-2 tracking-widest">ШАГ 3</div><h4 class="font-bold text-gray-800 mb-2">Дистрибуция цены</h4><p class="text-xs text-gray-500">Авто-обновление ESL ценников и Push-уведомления</p></div>
            </div>
        </section>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8">
            <div class="corp-card p-6 sm:p-8 flex flex-col">
                <div class="flex items-center mb-4 border-b border-gray-100 pb-4"><span class="section-marker">04</span><h3 class="text-lg sm:text-xl font-bold text-gray-800">Эластичность (ML Модель)</h3></div>
                <p class="text-sm text-gray-600 mb-4">График показывает зависимость вероятности покупки от размера скидки и оставшегося времени жизни товара.</p>
                <div class="w-full flex-grow border border-gray-100 rounded-lg bg-white overflow-hidden"><div class="plotly-container" id="elasticityPlot"></div></div>
            </div>
            <div class="corp-card p-6 sm:p-8 flex flex-col">
                <div class="flex items-center mb-4 border-b border-gray-100 pb-4"><span class="section-marker">05</span><h3 class="text-lg sm:text-xl font-bold text-gray-800">Unit-экономика (P&L)</h3></div>
                <p class="text-sm text-gray-600 mb-4">Финансовая модель MVP демонстрирует рост валовой прибыли за счет радикального сокращения объемов утилизации.</p>
                <div class="w-full flex-grow"><div class="chart-container"><canvas id="financeChart"></canvas></div></div>
            </div>
        </div>

        <section class="corp-card p-6 sm:p-8">
            <div class="flex items-center mb-8 border-b border-gray-100 pb-4"><span class="section-marker">06</span><h3 class="text-xl sm:text-2xl font-bold text-gray-800">Roadmap Масштабирования</h3></div>
            <div class="relative mt-8">
                <div class="hidden md:block roadmap-line-desktop"></div>
                <div class="grid grid-cols-1 md:grid-cols-4 gap-8 relative z-10">
                    <div class="flex flex-col md:items-center md:text-center relative pl-8 md:pl-0 border-l-2 md:border-l-0 border-gray-200"><div class="absolute left-[-9px] md:relative md:left-0 w-4 h-4 rounded-full bg-white border-4 border-[#59A83F] mb-4 shadow-sm"></div><span class="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Месяц 1-2</span><h4 class="text-base font-bold text-gray-900 mb-2">Пилот (5 РТО)</h4><p class="text-xs text-gray-600">Ручная маркировка желтыми стикерами. Сбор первичных данных.</p></div>
                    <div class="flex flex-col md:items-center md:text-center relative pl-8 md:pl-0 border-l-2 md:border-l-0 border-gray-200"><div class="absolute left-[-9px] md:relative md:left-0 w-4 h-4 rounded-full bg-white border-4 border-[#59A83F] mb-4 shadow-sm"></div><span class="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Месяц 3-4</span><h4 class="text-base font-bold text-gray-900 mb-2">MVP & App</h4><p class="text-xs text-gray-600">Интеграция в кассы 50 магазинов. Запуск "Спаси еду" в приложении.</p></div>
                    <div class="flex flex-col md:items-center md:text-center relative pl-8 md:pl-0 border-l-2 md:border-l-0 border-gray-200"><div class="absolute left-[-9px] md:relative md:left-0 w-4 h-4 rounded-full bg-white border-4 border-[#59A83F] mb-4 shadow-sm"></div><span class="text-xs font-bold text-gray-500 uppercase tracking-widest mb-1">Месяц 5-6</span><h4 class="text-base font-bold text-gray-900 mb-2">Анализ Churn</h4><p class="text-xs text-gray-600">Когортный анализ. Валидация отсутствия каннибализации.</p></div>
                    <div class="flex flex-col md:items-center md:text-center relative pl-8 md:pl-0 border-l-2 md:border-l-0 border-[#59A83F]"><div class="absolute left-[-9px] md:relative md:left-0 w-4 h-4 rounded-full bg-[#59A83F] border-4 border-[#59A83F] mb-4 shadow-sm animate-pulse"></div><span class="text-xs font-bold text-[#59A83F] uppercase tracking-widest mb-1">Месяц 7+</span><h4 class="text-base font-bold text-gray-900 mb-2">Rollout (ESL)</h4><p class="text-xs text-gray-600">Масштабирование. Интеграция с электронными ценниками.</p></div>
                </div>
            </div>
        </section>
    </main>

    <script>
        const colors = { green: '#59A83F', red: '#EF4444', grayDark: '#374151', grayLight: '#D1D5DB', grayBg: '#F3F4F6' };
        Chart.defaults.font.family = "'Inter', sans-serif";
        Chart.defaults.color = colors.grayDark;
        const tooltipConfig = { callbacks: { title: (tooltipItems) => { let label = tooltipItems[0].chart.data.labels[tooltipItems[0].dataIndex]; return Array.isArray(label) ? label.join(' ') : label; } } };
        const baseOptions = { responsive: true, maintainAspectRatio: false, plugins: { legend: { position: 'bottom', labels: { boxWidth: 12, padding: 20 } }, tooltip: tooltipConfig } };

        new Chart(document.getElementById('wastageChart').getContext('2d'), { type: 'doughnut', data: { labels: [['Доля в выручке', '(Реализация)'], ['Доля в списаниях', '(Убыток)'], ['Прочие категории', '']], datasets: [{ data: [5, 45, 50], backgroundColor: [colors.green, colors.red, colors.grayBg], borderWidth: 2, borderColor: '#ffffff' }] }, options: { ...baseOptions, cutout: '65%', layout: { padding: 10 } } });
        new Chart(document.getElementById('consumerChart').getContext('2d'), { type: 'radar', data: { labels: [['Фактор', 'цены'], ['Срок', 'годности'], ['Бренд', 'секрет'], ['Объем', 'порции'], ['Спонтанность', 'покупки']], datasets: [{ label: 'Базис (До 2024)', data: [60, 80, 70, 80, 65], backgroundColor: 'rgba(209, 213, 219, 0.4)', borderColor: colors.grayLight, pointBackgroundColor: colors.grayLight, borderWidth: 2 }, { label: 'Тренды 2026', data: [95, 85, 40, 60, 30], backgroundColor: 'rgba(89, 168, 63, 0.2)', borderColor: colors.green, pointBackgroundColor: colors.green, borderWidth: 2 }] }, options: { ...baseOptions, scales: { r: { angleLines: { color: 'rgba(0,0,0,0.05)' }, grid: { color: 'rgba(0,0,0,0.05)' }, ticks: { display: false, min: 0, max: 100 } } } } });
        new Chart(document.getElementById('financeChart').getContext('2d'), { type: 'bar', data: { labels: [['Статус-кво', '(Без уценки)'], ['Внедрение MVP', '(Smart Markdown)']], datasets: [{ label: 'Себестоимость', data: [40, 40], backgroundColor: colors.grayLight }, { label: 'Списания (Убыток)', data: [25, 5], backgroundColor: colors.red }, { label: 'Валовая маржа', data: [15, 22], backgroundColor: colors.green }] }, options: { ...baseOptions, scales: { x: { stacked: true, grid: { display: false } }, y: { stacked: true, grid: { color: 'rgba(0,0,0,0.05)' }, title: { display: true, text: 'млн. руб. / мес.' } } } } });

        const xData = [], yData = [], zData = [];
        for (let t = 2; t <= 24; t += 2) { for (let d = 10; d <= 60; d += 10) { xData.push(t); yData.push(d); let prob = (d / 100) * (t / 24) * 100; if (t <= 4) prob *= 0.3; zData.push(Math.max(5, Math.min(prob * 1.5, 95))); } }
        Plotly.newPlot('elasticityPlot', [{ x: xData, y: yData, z: zData, mode: 'markers', marker: { size: 5, color: zData, colorscale: [ [0, colors.red], [0.5, '#F59E0B'], [1, colors.green] ], opacity: 0.9, line: { width: 0.5, color: '#fff' } }, type: 'scatter3d', name: 'Конверсия' }], { margin: { l: 0, r: 0, b: 0, t: 0 }, paper_bgcolor: 'rgba(0,0,0,0)', plot_bgcolor: 'rgba(0,0,0,0)', font: { family: 'Inter', color: colors.grayDark, size: 10 }, scene: { xaxis: { title: 'Часы до списания', gridcolor: '#E5E7EB', backgroundcolor: '#F9FAFB', showbackground: true }, yaxis: { title: 'Скидка (%)', gridcolor: '#E5E7EB', backgroundcolor: '#F9FAFB', showbackground: true }, zaxis: { title: 'Покупка (%)', gridcolor: '#E5E7EB', backgroundcolor: '#F9FAFB', showbackground: true }, camera: { eye: {x: 1.5, y: 1.5, z: 0.5} } } }, { displayModeBar: false, responsive: true });
    </script>
</body>
</html>
"""

# 4. Рендеринг HTML внутри Streamlit на всю доступную высоту
components.html(html_content, height=2200, scrolling=False)